#include "StdAfx.h"

#if AveCompiler == AveCompilerVc && AvePlatform == AvePlatformWinDesktop
AveWinEnableCC6VS;
#	if AveArch == AveArchX64
#		pragma comment ( lib, "../../External/node-gyp/12.16.2/x64/node" )
#		if 1 == AveDebug
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Debug/Avernakis" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Debug/Avernakis-System" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Debug/Avernakis-Io" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Debug/Avernakis-Gui" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Debug/Avernakis-Gui-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Debug/Avernakis-Text" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Debug/Avernakis-Atelier" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Debug/Avernakis-Byo-3" )
#		elif !defined(AveLib)
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-System" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Io" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Gui" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Gui-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Text" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Sek" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Dee" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Byo-2" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_Release/Avernakis-Atelier" )
#		else
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-System" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Io" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Gui" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Gui-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Text" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Text-Script" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Sek" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Dee" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Byo-2" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Byo-3" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Atelier" )

#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-System.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Io.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Gui.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Dee.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Byo-2.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x64_ReleaseStatic/Avernakis-Byo-3.WinDesktop.lib" )
#		endif
#	elif AveArch == AveArchX86
#		if 1 == AveDebug
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Debug/Avernakis" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Debug/Avernakis-System" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Debug/Avernakis-Io" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Debug/Avernakis-Gui" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Debug/Avernakis-Gui-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Debug/Avernakis-Text" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Debug/Avernakis-Atelier" )
#		elif !defined(AveLib)
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-System" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Io" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Gui" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Gui-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Text" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Sek" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Dee" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Byo-2" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_Release/Avernakis-Atelier" )
#		else
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-System" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Io" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Gui" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Gui-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Text" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Sek" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Dee" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Byo-2" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Image" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Atelier" )

#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-System.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Io.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Gui.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Dee.WinDesktop.lib" )
#			pragma comment ( lib, "../../External/Avernakis/Library/WinDesktop_x86_ReleaseStatic/Avernakis-Byo-2.WinDesktop.lib" )
#		endif
#	endif
#endif
