name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          cd "Code/Avernakis Nodejs/Test-Nodejs"
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
