name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: publish npm package
        run: |
          cd "Code/Avernakis Nodejs/Test-Nodejs"
          npm ci
          npm run build
          npm test
        env:
          CI: true
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
